services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: front-dev
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - eigakanban
    depends_on:
      - api
      - db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: go-dev
    ports:
      - "8080:8080"
    env_file:
      - api/.env
    networks:
      - eigakanban
    volumes:
      - ./api:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - api/.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - eigakanban
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

networks:
  eigakanban:
    driver: bridge

volumes:
  db:
    driver: local
  front-node-modules: