services:
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - api/.env
    environment:
      POSTGRES_DB: eigakanban
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local