// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	BoardID     pgtype.Int8        `json:"board_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	UserID      pgtype.Int8        `json:"user_id"`
	CreatedDate pgtype.Timestamptz `json:"created_date"`
}

type ColumnItem struct {
	ColumnItemID pgtype.Int8        `json:"column_item_id"`
	ColumnID     pgtype.Int8        `json:"column_id"`
	ItemID       pgtype.Int8        `json:"item_id"`
	UserID       pgtype.Int8        `json:"user_id"`
	CreatedDate  pgtype.Timestamptz `json:"created_date"`
	Position     pgtype.Int4        `json:"position"`
}

type Item struct {
	ItemID      pgtype.Int8        `json:"item_id"`
	Title       string             `json:"title"`
	StatusID    pgtype.Int8        `json:"status_id"`
	CreatedDate pgtype.Timestamptz `json:"created_date"`
}

type Kbcolumn struct {
	ColumnID    pgtype.Int8        `json:"column_id"`
	Name        string             `json:"name"`
	BoardID     pgtype.Int8        `json:"board_id"`
	UserID      pgtype.Int8        `json:"user_id"`
	Position    int32              `json:"position"`
	CreatedDate pgtype.Timestamptz `json:"created_date"`
}

type Review struct {
	ReviewID    pgtype.Int8        `json:"review_id"`
	Content     string             `json:"content"`
	UserID      pgtype.Int8        `json:"user_id"`
	ItemID      pgtype.Int8        `json:"item_id"`
	CreatedDate pgtype.Timestamptz `json:"created_date"`
}

type Status struct {
	StatusID    pgtype.Int8        `json:"status_id"`
	UserID      pgtype.Int8        `json:"user_id"`
	Label       pgtype.Text        `json:"label"`
	CreatedDate pgtype.Timestamptz `json:"created_date"`
}

type User struct {
	UserID         pgtype.Int8        `json:"user_id"`
	Username       string             `json:"username"`
	HashedPassword string             `json:"hashed_password"`
	Email          string             `json:"email"`
	FullName       pgtype.Text        `json:"full_name"`
	Bio            pgtype.Text        `json:"bio"`
	CreatedDate    pgtype.Timestamptz `json:"created_date"`
}
